version: '3'
services:
    app-api:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        ports:
            - '127.0.0.1:8080:8080'
        container_name: app-api
